/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JSplash;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author lenovo
 */
public class Newfilewindow extends javax.swing.JDialog {
    static public File[] file=new File[8];
    static public String[] filename=new String[8];
    static public String[] filepath=new String[8];
Newfilewindow window=null;
public static File diag=null; 
public static int add;

    /**
     * Creates new form Newprojectwindow
     */
    public Newfilewindow() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        browse = new javax.swing.JButton();
        finish = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        status = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(450, 190));

        projectname.setText("File  Name:");

        jLabel2.setText("Location:");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        browse.setText("Browse...");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        status.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Creat New File");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JSplash/Document-new-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(finish)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(location)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectname)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(status)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(finish))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
       String sd;
       sd=name.getText();
       if((sd.length()==0)||(location.getText().length()==0))
        status.setText("*Fields cannot be left blank");
       else
           if((JavaIDE.i)==6)
         status.setText("Tabs limit is reached.Close any other tab.");
       else
       if(file[JavaIDE.i]==null)
        {  
            filepath[JavaIDE.i]=location.getText();
            file[JavaIDE.i]= new File( filepath[JavaIDE.i]+"\\"+filename[JavaIDE.i]+".java");
            try{  if (!file[JavaIDE.i].exists()){ 
            file[JavaIDE.i].createNewFile(); } }catch(IOException e){};
            
            JavaIDE.filenode[JavaIDE.i]= new DefaultMutableTreeNode(filename[JavaIDE.i]+".java");    
                  if(JavaIDE.treenode.getLevel()==0)
           { JavaIDE.node[Newprojectwindow.n]=new DefaultMutableTreeNode("default");
           add=Newprojectwindow.n;
             JavaIDE.treenode.add(JavaIDE.node[Newprojectwindow.n]);
             JavaIDE.node[Newprojectwindow.n].add(JavaIDE.filenode[JavaIDE.i]);
            }
         else
         {   boolean flag=false;
             String parent=file[JavaIDE.i].getParent();
             for(int k=0;k<=Newprojectwindow.n;k++){
                 if(JavaIDE.node[k].toString()==parent){
              JavaIDE.node[k].insert(JavaIDE.filenode[JavaIDE.i],JavaIDE.node[k].getChildCount()+1);
              flag=true;   
             }
              if(flag==false){ 
                  if(add!=0){
              JavaIDE.node[Newprojectwindow.n]=new DefaultMutableTreeNode("default");
              JavaIDE.treenode.insert(JavaIDE.node[Newprojectwindow.n],JavaIDE.treenode.getChildCount()+1);
              JavaIDE.node[Newprojectwindow.n].add(JavaIDE.filenode[JavaIDE.i]);
                  }
                  else{
            JavaIDE.node[add].insert(JavaIDE.filenode[JavaIDE.i], JavaIDE.node[Newprojectwindow.n].getChildCount()+1);
                  }
             flag=false;           
                         }
             }
          
         }
        
         
        JavaIDE.createtab(filename[JavaIDE.i]+".java");
        JavaIDE.programs.setSelectedIndex(JavaIDE.i);
        dispose();
        }
         else{
           file[JavaIDE.i]= new File(filepath[JavaIDE.i]+"\\"+filename[JavaIDE.i]+".java");
          try{  if (!file[JavaIDE.i].exists()){ 
            file[JavaIDE.i].createNewFile(); } }catch(IOException e){};
            if(JavaIDE.node==null)
            {JavaIDE.node[Newprojectwindow.n]=new DefaultMutableTreeNode("default");
             JavaIDE.treenode.add(JavaIDE.node[Newprojectwindow.n]);
            }
             JavaIDE.filenode[JavaIDE.i]= new DefaultMutableTreeNode(filename[JavaIDE.i]+".java");
         JavaIDE.node[Newprojectwindow.n].add(JavaIDE.filenode[JavaIDE.i]); 
         JavaIDE.createtab(filename[JavaIDE.i]+".java");
        JavaIDE.programs.setSelectedIndex(JavaIDE.i);   
         dispose(); 
            
       }
     
    }//GEN-LAST:event_finishActionPerformed

  
      
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    
    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser fc=new JFileChooser();
         fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      int response=fc.showSaveDialog(Newfilewindow.this);
       if(response==JFileChooser.APPROVE_OPTION){
        File file= fc.getSelectedFile();
        filename[JavaIDE.i]=name.getText().trim();
         filepath[JavaIDE.i]=file.getAbsolutePath();
         location.setText(filepath[JavaIDE.i]);
                     
       }
    }//GEN-LAST:event_browseActionPerformed
public void makefilewindow(){
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Newfilewindow dialog = new Newfilewindow();
                window=dialog;
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    }
                });
                dialog.setVisible(true);
            }
        });
  
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton cancel;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    private javax.swing.JLabel projectname;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
